config/routes.rb
Rails.application.routes.draw do
  resources :clients
  #devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(
    controllers: { sessions: 'admin_users/sessions' }
  )
  ActiveAdmin.routes(self)
  devise_for :users
  
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable


    def self.ransackable_attributes(auth_object = nil)
    %w[name email]
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        %w[name email phone created_at]
      end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




  after_save :create_crm_contact, if: :saved_change_to_current_sign_in_at?

    private
  
    def update_crm_contact
      Contact.find_or_create_by(email: email) do |contact|
        contact.name = name
      end
    end
end

app/controllers/admin_users/sessions_controller.rb
# frozen_string_literal: true

class AdminUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


  after_action :create_crm_contact, only: [:create]

  private

  def create_crm_contact
    if admin_user_signed_in?
      Contact.create(name: "Contact Info", email: current_admin_user.email)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base

  private

    def client_params
      params.require(:client).permit(:name, :email, :phone)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController 

    def index
        @contacts = Contact.all
    end


    def show 
        @user = Contact.find(params[:id])
        @name = @user.email.split('@')[0]
        @contact =  Contact.where(:email => @user.email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= client.phone %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/contacts/index.html.erb
<div class="container mt-5">   
    <h1 class="display-4 mb-4 text-center">Emails who logged in </h1>

    <% @contacts.group_by(&:email).each do |email, contacts| %>
    <% contact = contacts.first %>
    <div class="record-card">
        <h4>Email: <span class="text-primary"><%= contact.email %></span></h4>
        <h4>Created At: <span class="text-secondary"><%= contact.created_at.strftime("%B %d, %Y %H:%M") %></span></h4>
        <%= link_to 'Show all details', contact_path(contact) %>
    </div>
    <hr>
    <% end %>
</div>

app/views/contacts/show.html.erb
<div class="container mt-5">
        <h1 class="display-4 mb-4 text-center">All Records of <%= @name %> Logins</h1>

        <% @contact.each do |contact| %> 
        <div class="record-card">
            <h4>Email: <span class="text-primary"><%= contact.email %></span></h4> 
            <h4>Logged In on: <span class="text-secondary"><%= contact.created_at.strftime("%B %d, %Y %H:%M") %></span></h4>
        </div>
        <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
        <style>
        .record-card {
            margin-bottom: 20px;
            padding: 20px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            background-color: #f8f9fa;
        }
        .record-card h4 {
            margin-bottom: 10px;
        }
    </style>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>